### PR TITLE
add crude handshake needed by Benq W1070 while in power save mode

### PR DESCRIPTION
**Pull request by leakim**
Can someone test this code since I don't have a Benq projector?

### CODE REVIEW

**Comment by JohnBrodie** [comment]
I might be able to test this over the weekend.

**Comment by JohnBrodie** [comment]
Works as expected.  Thanks again @leakim

**Comment by plajjan** [comment]
Just wanted to add that I think this hand shake is expected at all times and not just in power save mode. At least that was my interpretation from reading the docs. The code appears to be doing the right thing, just the commit message is slightly misleading.

Also, a wait of 1 second seems long. I'd rather have a select() or busy loop around that. My projector usually returns "instantaneously" so waiting 1 second for every command I want to run seems long.

**Comment by leakim** [comment]
I agree @plajjan 
the first code I wrote actually used blocking read (select) but I could not get it to work correctly and I did not want to spend time on it. My reasoning was that if I would refactor this then I would do so breaking out the serial calls to some callbacks and then use twisted for all io or some other method (ie socket) chosen by the user of the library. I wrote some code for that too that worked well but I never submitted that code as it would break the current design.

The current delay of 1 second is just out of laziness. The delay should be a function of the baud rate + latency.

**Comment by plajjan** [comment]
@leakim I just fiddled a bit with select which works fine for the handshake since we are just expecting one character. As soon as that character is seen we do a read and can continue.

The problem was with get_response(). I tried adding a select in there before the `while self.serial.inWaiting()`  While it correctly blocks for a short amount of time I ended up getting only part of the actual response due to the slow nature of the serial port. We are reading faster than the data comes in so getting a truncated response:

```
kll@PompousTheather:~/pyjector$ ./pyjector_controller -v benq /dev/ttyUSB0 power status
1445960224.751555 INFO send: '*pow=?#\r'
1445960225.771365 INFO recv: '*p'
```

Since we actually know what we want, i.e. we know how the end of the response looks like, I guess we should be waiting until we see that but it requires a little bit more coding and touches more than just benq so I'm wary of going there.

**Comment by JohnBrodie** [comment]
@plajjan - Now that we have a few people whom can test, if you'd like to make farther-reaching changes, have at it.  I wrote this when I was a student, and stopped developing it basically as soon as I wrote enough of it to meet my needs, so there's plenty to improve.

**Comment by plajjan** [comment]
I'll admit that I'm not actually using it. I set out to use OpenHAB for my home automation stuff and it has a Benq projector binding but it was using some network-to-serial-adapter that I didn't have. Rather than starting out with it I turned to pyjector just to make sure my setup with local serial port worked, like that I had the correct serial cable (I dug it out an old box full of cables) and so forth. Once I had seen it was working with pyjector I moved on to write a serial transport for OpenHABs Benq projector binding (https://github.com/openhab/openhab/pull/3330). Also, I'm not a Java person so using Python to write an initial implementation gave me some experience in how to do it :)

I only spent time on select() for the fun of it ;) Not sure how much time I can spend moving forward...

**Pull request merged**
